package de.hska.wi.awp.datasource.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.hska.wi.awp.datasource.model.Commit;
import de.hska.wi.awp.datasource.service.CommitLocalServiceUtil;

/**
 * The extended model base implementation for the Commit service. Represents a row in the &quot;gitlab_Commit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommitImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CommitImpl
 * @see de.hska.wi.awp.datasource.model.Commit
 * @generated
 */
public abstract class CommitBaseImpl extends CommitModelImpl implements Commit {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a commit model instance should use the {@link Commit} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CommitLocalServiceUtil.addCommit(this);
        } else {
            CommitLocalServiceUtil.updateCommit(this);
        }
    }
}
