package de.hska.wi.awp.datasource.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Contributor service. Represents a row in the &quot;gitlab_Contributor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.hska.wi.awp.datasource.model.impl.ContributorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.hska.wi.awp.datasource.model.impl.ContributorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Contributor
 * @see de.hska.wi.awp.datasource.model.impl.ContributorImpl
 * @see de.hska.wi.awp.datasource.model.impl.ContributorModelImpl
 * @generated
 */
public interface ContributorModel extends BaseModel<Contributor> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a contributor model instance should use the {@link Contributor} interface instead.
     */

    /**
     * Returns the primary key of this contributor.
     *
     * @return the primary key of this contributor
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this contributor.
     *
     * @param primaryKey the primary key of this contributor
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the contributor ID of this contributor.
     *
     * @return the contributor ID of this contributor
     */
    public long getContributorId();

    /**
     * Sets the contributor ID of this contributor.
     *
     * @param contributorId the contributor ID of this contributor
     */
    public void setContributorId(long contributorId);

    /**
     * Returns the name of this contributor.
     *
     * @return the name of this contributor
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this contributor.
     *
     * @param name the name of this contributor
     */
    public void setName(String name);

    /**
     * Returns the email of this contributor.
     *
     * @return the email of this contributor
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this contributor.
     *
     * @param email the email of this contributor
     */
    public void setEmail(String email);

    /**
     * Returns the commits of this contributor.
     *
     * @return the commits of this contributor
     */
    public int getCommits();

    /**
     * Sets the commits of this contributor.
     *
     * @param commits the commits of this contributor
     */
    public void setCommits(int commits);

    /**
     * Returns the loc additions of this contributor.
     *
     * @return the loc additions of this contributor
     */
    public int getLocAdditions();

    /**
     * Sets the loc additions of this contributor.
     *
     * @param locAdditions the loc additions of this contributor
     */
    public void setLocAdditions(int locAdditions);

    /**
     * Returns the loc deletions of this contributor.
     *
     * @return the loc deletions of this contributor
     */
    public int getLocDeletions();

    /**
     * Sets the loc deletions of this contributor.
     *
     * @param locDeletions the loc deletions of this contributor
     */
    public void setLocDeletions(int locDeletions);

    /**
     * Returns the project name of this contributor.
     *
     * @return the project name of this contributor
     */
    @AutoEscape
    public String getProjectName();

    /**
     * Sets the project name of this contributor.
     *
     * @param projectName the project name of this contributor
     */
    public void setProjectName(String projectName);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        de.hska.wi.awp.datasource.model.Contributor contributor);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.hska.wi.awp.datasource.model.Contributor> toCacheModel();

    @Override
    public de.hska.wi.awp.datasource.model.Contributor toEscapedModel();

    @Override
    public de.hska.wi.awp.datasource.model.Contributor toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
